package com.AlexNewg.youtube.console.ui;

/**
 * Created by Alex on 16.07.2017.
 */
public enum State {
    STARTED,
    MAIN_MENU,
    CONTACT_MENU,
    GROUP_MENU,
    FINISHED,
    CREATE_GROUP,
    DELETE_GROUP,
    UNKNOWN,
    UPDATE_GROUP,
    DETAILED_CONTACT,
    CREATE_CONTACT,
    UPDATE_CONTACT_NAME,
    UPDATE_CONTACT_DESCRIPTION,
    DELETE_CONTACT,
    ADD_GROUP_TO_CONTACT,
    REMOVE_GROUP_FROM_CONTACT,
    SHOW_ALL_MEMBERS_OF_A_GROUP
}
